// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MOG_TitleCommands","status":false,"description":"(v1.3)MOG标题图片选项","parameters":{"-> Main <<<<<<<<<<<<<<<<<<<<<<<":"","Animation Mode":"2","Left & Right Input":"true","Shake Duration":"30","Slide X-Axis":"-100","Slide Y-Axis":"0","-> Cursor <<<<<<<<<<<<<<<<<<<<<<<":"","Cursor X-Axis":"0","Cursor Y-Axis":"5","Cursor Visible":"true","Cursor Wave Animation":"true","Cursor Rotation Animation":"false","Cursor Rotation Speed":"0.05","-> Commands <<<<<<<<<<<<<<<<<<<<<<<":"","Command Pos 1":"65,150","Command Pos 2":"65,200","Command Pos 3":"65,250","Command Pos 4":"65,300","Command Pos 5":"345,498","Command Pos 6":"345,530","Command Pos 7":"0,192","Command Pos 8":"0,224","Command Pos 9":"0,256","Command Pos 10":"0,288"}}
];
